--- DATABASE CREATION SCRIPT
Create DATABASE VLCMS;
-- USE THE DATABASE
USE VLCMS;

-- OWNER TABLE CREATION SCRIPT
CREATE TABLE OWNER (
    Owner_Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Phone_No VARCHAR(15) UNIQUE NOT NULL,
    Email_Id VARCHAR(50) UNIQUE,
    Address VARCHAR(255),
    Gender ENUM('Male', 'Female', 'Other') NOT NULL
);

-- VEHICLES TABLE CREATION SCRIPT
CREATE TABLE VEHICLES (
    Vehicle_Id INT AUTO_INCREMENT UNIQUE,
    Reg_Num VARCHAR(14)  PRIMARY KEY ,
    Make VARCHAR(50),
    Model VARCHAR(50),
    Year INT,
    Milage INT,
    Owner_Id INT NOT NULL,
    FOREIGN KEY (Owner_Id) REFERENCES OWNER(Owner_Id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- WORKSHOP TABLE CREATION SCRIPT
CREATE TABLE WORKSHOP (
    WorkShop_Id INT PRIMARY KEY ,
    Name VARCHAR(100) NOT NULL,
    Phone_No VARCHAR(15) UNIQUE NOT NULL,
    Email_Id VARCHAR(50) UNIQUE,
    Location VARCHAR(255),
    CHECK (Phone_No REGEXP '^[0-9]{10}$')
);

-- SERVICE RECORD TABLE CREATION SCRIPT
CREATE TABLE SERVICE_RECORD (
    Service_Id INT PRIMARY KEY AUTO_INCREMENT,
    Service_Cost DECIMAL(10, 2),
    Service_type VARCHAR(100),
    Service_Date DATE,
    Odometer_Readings INT,
    Remark TEXT,
    WorkShop_Id INT, 
    Reg_Num VARCHAR(14) NOT NULL,
    FOREIGN KEY (WorkShop_Id) REFERENCES WORKSHOP(WorkShop_Id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (Reg_Num) REFERENCES VEHICLES(Reg_Num) ON DELETE CASCADE ON UPDATE CASCADE

);

-- SERVICE TASK TABLE CREATION SCRIPT
CREATE TABLE SERVICE_TASK (
    Service_Task_Id INT PRIMARY KEY AUTO_INCREMENT,
    Description TEXT NOT NULL,
    Cost DECIMAL(10, 2),
    Service_Id INT NOT NULL,
    FOREIGN KEY (Service_Id) REFERENCES SERVICE_RECORD(Service_Id) ON DELETE CASCADE On UPDATE CASCADE
);

-- PART TABLE CREATION SCRIPT
CREATE TABLE PART (
    Part_Id VARCHAR(30) PRIMARY KEY,   -- e.g., 'BRK001' or 'ENG045'
    Part_No VARCHAR(50) NOT NULL,      -- manufacturer or internal number
    Name VARCHAR(100),
    Warranty_Period INT,               -- in months
    Service_Task_Id INT NOT NULL,
    FOREIGN KEY (Service_Task_Id) REFERENCES SERVICE_TASK(Service_Task_Id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- PART REPLACEMENT TABLE CREATION SCRIPT
CREATE TABLE PART_REPLACEMENT (
    Replacement_Id INT PRIMARY KEY AUTO_INCREMENT,
    Part_Cost DECIMAL(10, 2),
    Replacement_Date DATE,
    Warranty_Period INT,
    Service_Task_Id INT NOT NULL,
    FOREIGN KEY (Service_Task_Id) REFERENCES SERVICE_TASK(Service_Task_Id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- WARRANTY CLAIM TABLE CREATION SCRIPT
CREATE TABLE WARRANTY_CLAIM (
    Claim_Id INT PRIMARY KEY ,
    Status VARCHAR(50),
    Date DATE,
    Replacement_Id INT NOT NULL,
    FOREIGN KEY (Replacement_Id) REFERENCES PART_REPLACEMENT(Replacement_Id) ON DELETE CASCADE On UPDATE CASCADE
);

-- INSURANCE TABLE CREATION SCRIPT
CREATE TABLE INSURANCE (
    Insurance_Id INT PRIMARY KEY ,
    Provider VARCHAR(100),
    Policy_No VARCHAR(50) NOT NULL UNIQUE,
    Expiry_Date DATE,
    Reg_Num VARCHAR(14) NOT NULL,
    FOREIGN KEY (Reg_Num) REFERENCES VEHICLES(Reg_Num) ON DELETE CASCADE
);
